// Code generated by Kitex v0.10.1. DO NOT EDIT.

package raft_operations

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	api "zhuMQ/kitex_gen/api"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	RequestVote(ctx context.Context, rep *api.RequestVoteArgs_, callOptions ...callopt.Option) (r *api.RequestVoteReply, err error)
	AppendEntries(ctx context.Context, rep *api.AppendEntriesArgs_, callOptions ...callopt.Option) (r *api.AppendEntriesReply, err error)
	SnapShot(ctx context.Context, rep *api.SnapShotArgs_, callOptions ...callopt.Option) (r *api.SnapShotReply, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kRaft_OperationsClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kRaft_OperationsClient struct {
	*kClient
}

func (p *kRaft_OperationsClient) RequestVote(ctx context.Context, rep *api.RequestVoteArgs_, callOptions ...callopt.Option) (r *api.RequestVoteReply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.RequestVote(ctx, rep)
}

func (p *kRaft_OperationsClient) AppendEntries(ctx context.Context, rep *api.AppendEntriesArgs_, callOptions ...callopt.Option) (r *api.AppendEntriesReply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AppendEntries(ctx, rep)
}

func (p *kRaft_OperationsClient) SnapShot(ctx context.Context, rep *api.SnapShotArgs_, callOptions ...callopt.Option) (r *api.SnapShotReply, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SnapShot(ctx, rep)
}
